name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --release --verbose

          #- name: Run tests
          #  run: cargo test --verbose

      - name: Install agb-gbafix
        run: cargo install agb-gbafix

      - name: Update binary for hardware
        run: agb-gbafix target/thumbv4t-none-eabi/release/whitch --output whitch.gba --gamecode WTCH --makercode N8

      - name: Upload development release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            whitch.gba

      - name: Upload release
        uses: marvinpinto/action-automatic-releases@latest
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            whitch.gba
